## code to prepare `branches` dataset goes here
branches <- data.frame(
  branch = c(
    "01_whole-app-game",
    "02.1_shiny-app",
    "02.2_movies-app",
    "02.3_proj-app",
    "03.1_description",
    "03.2_rproj",
    "03.3_create-package",
    "04_devtools",
    "05_roxygen2",
    "06.1_pkg-exports",
    "06.2_pkg-imports",
    "07_data",
    "08_launch-app",
    "09_inst",
    "10_debugger",
    "11_debug-print",
    "12.1_debug-mods",
    "12.2_mod-comms",
    "13_logging",
    "14_tests_suite",
    "15_specs",
    "16.1_test-help",
    "16.2_test-data",
    "16.3_test-logger",
    "16.4_test-snapshots",
    "17_test-modules",
    "18_test-system",
    "19_shinyappsio",
    "20_docker",
    "21.1_gha-style",
    "21.2_gha-shiny-deploy",
    "21.3_gha-shiny-docker",
    "22_pkgdown",
    "23_llm-shiny-assist",
    "24_llm-ellmer",
    "25_llm-shinychat",
    "26_llm-chores",
    "27_golem",
    "28_leprechaun",
    "29_rhino",
    "DEV",
    "gh-pages",
    "main"
  ))
usethis::use_data(branches, overwrite = TRUE)
