## code to prepare `branches` dataset goes here
branches <- data.frame(branch = c("01_whole-app-game",
                       "02.1_shiny-app","02.2_movies-app","02.3_proj-app",
                       "03.1_description","03.2_rproj","03.3_create-package","04_devtools",
                       "05_roxygen2","06.1_pkg-exports","06.2_pkg-imports",
                       "07_data","08_launch-app","09.1_inst-www",
                       "09.2_inst-bslib","09.3_inst-dev","09.4_inst-prod",
                       "11_tests-specs","12.1_tests-fixtures","12.2_tests-helpers",
                       "13_tests-modules","14_tests-system","15_docker",
                       "16.1_cicd-style","16.2_cicd-shiny","16.3_cicd-docker","17_golem",
                       "18_leprechaun","19_rhino","20_css","21_js",
                       "22_python","22.1_reactive-values","22.2_user-data",
                       "23_tests-snapshots","23.1_debug-error","23.2_debug-selected_vars",
                       "23.3_debug-var_inputs","23.4_debug-scatter_plot",
                       "23.5_debug-print","24_app-data","24_tests-mocks",
                       "A_G-mocks-snapshots","HEAD","main","st_trace-matrix"))
usethis::use_data(branches, overwrite = TRUE)

topic_lookup <- data.frame(
            branch = c("01_whole-app-game",
                       "02.1_shiny-app","02.2_movies-app","02.3_proj-app",
                       "03.1_description","03.2_rproj","03.3_create-package","04_devtools",
                       "05_roxygen2","06.1_pkg-exports","06.2_pkg-imports",
                       "07_data","08_launch-app","09.1_inst-www",
                       "09.2_inst-bslib","09.3_inst-dev","09.4_inst-prod",
                       "11_tests-specs","12.1_tests-fixtures","12.2_tests-helpers",
                       "13_tests-modules","14_tests-system","15_docker",
                       "16.1_cicd-style","16.2_cicd-shiny","16.3_cicd-docker","17_golem",
                       "18_leprechaun","19_rhino","20_css","21_js",
                       "22_python","22.1_reactive-values","22.2_user-data",
                       "23_tests-snapshots","23.1_debug-error","23.2_debug-selected_vars",
                       "23.3_debug-var_inputs","23.4_debug-scatter_plot",
                       "23.5_debug-print","24_app-data","24_tests-mocks",
                       "A_G-mocks-snapshots","HEAD","main","st_trace-matrix"),
              part = c("Intro","Intro","Intro",
                       "Intro","Intro","Intro","Intro","Intro","App-packages",
                       "App-packages","App-packages","App-packages",
                       "App-packages","App-packages","App-packages","App-packages",
                       "App-packages","Tests","Tests","Tests","Tests","Tests",
                       "Deploy","Deploy","Deploy","Deploy","Frameworks",
                       "Frameworks","Frameworks","Non-R Code","Non-R Code",
                       "Non-R Code","Deprecated","Deprecated","Special Topics",
                       "Special Topics","Special Topics","Special Topics",
                       "Special Topics","Special Topics","Special Topics",
                       "Deprecated","Appendix",NA,NA,"Appendix"),
           chapter = c("Whole app game","Shiny",
                       "Shiny","Shiny","Packages","Packages","Packages",
                       "Development","Documentation","Dependencies","Dependencies",
                       "Data","Launch","External files","External files",
                       "External files","External files","Specifications",
                       "Test tools","Test tools","Testing modules","System tests",
                       "Docker","CI/CD","CI/CD","CI/CD","golem",
                       "leprechaun","rhino","CSS","JavaScript","Python","Deprecated",
                       "Deprecated","Values vs. data","Debugging","Debugging",
                       "Debugging","Debugging","Debugging",
                       "Values vs. data","Deprecated","Test mocks and snapshots",NA,NA,
                       "Traceability Matrix")
)

usethis::use_data(topic_lookup, overwrite = TRUE)
