## code to prepare `branches` dataset goes here
branches <- data.frame(branch = c("01_whole-app-game",
                       "02.1_shiny-app","02.2_movies-app","02.3_proj-app",
                       "03.1_description","03.2_rproj","03.3_create-package","04_devtools",
                       "05_roxygen2","06.1_pkg-exports","06.2_pkg-imports",
                       "07_data","08_launch-app","09.1_inst-www",
                       "09.2_inst-bslib","09.3_inst-dev","09.4_inst-prod",
                       "11_tests-specs","12.1_tests-fixtures","12.2_tests-helpers",
                       "12.3_tests-snapshots","13_tests-modules","14_tests-system",
                       "15_docker","16.1_gha-style","16.2_gha-shiny",
                       "16.3_gha-docker","17_pkgdown","18.1_css-inline",
                       "18.2_css-internal","18.3_css-file","19_js","20_python","21_style",
                       "22_golem","23_leprechaun","24_rhino",
                       "25.0_debug-error","25.1_debug-selected_vars","25.2_debug-var_inputs",
                       "25.3_debug-scatter_plot","25.4_debug-print",
                       "26.1.0_reactive-values","26.1.1_step_01","26.1.2_step_02",
                       "26.1.3_step_03","26.1.4_step_04","26.2.0_user-data",
                       "26.2.1_step_01","26.2.2_step_02","27_stack-traces",
                       "28_dependency-hell","A.E_mocks-snapshots"))
usethis::use_data(branches, overwrite = TRUE)

topic_lookup <- data.frame(
            branch = c("01_whole-app-game",
                       "02.1_shiny-app","02.2_movies-app","02.3_proj-app",
                       "03.1_description","03.2_rproj","03.3_create-package","04_devtools",
                       "05_roxygen2","06.1_pkg-exports","06.2_pkg-imports",
                       "07_data","08_launch-app","09.1_inst-www",
                       "09.2_inst-bslib","09.3_inst-dev","09.4_inst-prod",
                       "11_tests-specs","12.1_tests-fixtures","12.2_tests-helpers",
                       "12.3_tests-snapshots","13_tests-modules","14_tests-system",
                       "15_docker","16.1_gha-style","16.2_gha-shiny",
                       "16.3_gha-docker","17_pkgdown","18.1_css-inline",
                       "18.2_css-internal","18.3_css-file","19_js","20_python","21_style",
                       "22_golem","23_leprechaun","24_rhino",
                       "25.0_debug-error","25.1_debug-selected_vars","25.2_debug-var_inputs",
                       "25.3_debug-scatter_plot","25.4_debug-print",
                       "26.1.0_reactive-values","26.1.1_step_01","26.1.2_step_02",
                       "26.1.3_step_03","26.1.4_step_04","26.2.0_user-data",
                       "26.2.1_step_01","26.2.2_step_02","27_stack-traces",
                       "28_dependency-hell","A.E_mocks-snapshots"),
              part = c("Intro","Intro","Intro",
                       "Intro","Intro","Intro","Intro","Intro","App-packages",
                       "App-packages","App-packages","App-packages",
                       "App-packages","App-packages","App-packages","App-packages",
                       "App-packages","Tests","Tests","Tests","Tests","Tests",
                       "Deploy","Deploy","Deploy","Deploy","Deploy",
                       "Deploy","Non-R Code","Non-R Code","Non-R Code",
                       "Non-R Code","Non-R Code","Non-R Code","Frameworks",
                       "Frameworks","Frameworks","Special Topics","Special Topics",
                       "Special Topics","Special Topics","Special Topics",
                       "Special Topics","Special Topics","Special Topics",
                       "Special Topics","Special Topics","Special Topics",
                       "Special Topics","Special Topics","Special Topics","Special Topics",
                       "Appendix"),
           chapter = c("Whole app game","Shiny",
                       "Shiny","Shiny","Packages","Packages","Packages",
                       "Development","Documentation","Dependencies","Dependencies",
                       "Data","Launch","External files","External files",
                       "External files","External files","Specifications",
                       "Test tools","Test tools","Test tools","Testing modules",
                       "System tests","Docker","GitHub Actions",
                       "GitHub Actions","GitHub Actions","pkgdown","CSS","CSS","CSS",
                       "JavaScript","Python","Linting and styling","golem",
                       "leprechaun","rhino","Debugging","Debugging","Debugging",
                       "Debugging","Debugging","App Data","App Data",
                       "App Data","App Data","App Data","App Data","App Data",
                       "App Data","Stack traces","Dependency hell",
                       "Appendix E — Mocks and snapshots")
)

usethis::use_data(topic_lookup, overwrite = TRUE)
