## code to prepare `branches` dataset goes here
topic_lookup <- data.frame(
  branch = c(
    "01_whole-app-game",
    "02.1_shiny-app",
    "02.2_movies-app",
    "02.3_proj-app",
    "03.1_description",
    "03.2_rproj",
    "03.3_create-package",
    "04_devtools",
    "05_roxygen2",
    "06.1_pkg-exports",
    "06.2_pkg-imports",
    "07_data",
    "08_launch-app",
    "09_inst",
    "10_debugger",
    "11_debug-print",
    "12.1_debug-mods",
    "12.2_mod-comms",
    "13_logging",
    "14_tests_suite",
    "15_specs",
    "16.1_test-help",
    "16.2_test-data",
    "16.3_test-logger",
    "16.4_test-snapshots",
    "17_test-modules",
    "18_test-system",
    "19_shinyappsio",
    "20_docker",
    "21.1_gha-style",
    "21.2_gha-shiny-deploy",
    "21.3_gha-shiny-docker",
    "22_pkgdown",
    "23_llm-shiny-assist",
    "24_llm-ellmer",
    "25_llm-shinychat",
    "26_llm-chores",
    "27_golem",
    "28_leprechaun",
    "29_rhino",
    "DEV",
    "gh-pages",
    "main"
  ),
  part = c(
    "Intro",
    "Intro",
    "Intro",
    "Intro",
    "Intro",
    "Intro",
    "Intro",
    "Intro",
    "App-packages",
    "App-packages",
    "App-packages",
    "App-packages",
    "App-packages",
    "App-packages",
    "Debugging",
    "Debugging",
    "Debugging",
    "Debugging",
    "Debugging",
    "Tests",
    "Tests",
    "Tests",
    "Tests",
    "Tests",
    "Tests",
    "Tests",
    "Tests",
    "Deploy",
    "Deploy",
    "Deploy",
    "Deploy",
    "Deploy",
    "Deploy",
    "Shiny & LLMs",
    "Shiny & LLMs",
    "Shiny & LLMs",
    "Shiny & LLMs",
    "Frameworks",
    "Frameworks",
    "Frameworks",
    NA,
    NA,
    NA
  ),
  chapter = c(
    "Whole app game",
    "Shiny",
    "Shiny",
    "Shiny",
    "Packages",
    "Packages",
    "Packages",
    "Development",
    "Documentation",
    "Dependencies",
    "Dependencies",
    "Data",
    "Launch",
    "External files",
    "Debugging in Positron/RStudio",
    "Print debugging methods",
    "Debugging modules",
    "Debugging module communication",
    "Logging app behaviors",
    "Building testthat test suite",
    "Test specifications",
    "Using ensure to help write tests",
    "Storing and using test data",
    "Writing a test logging helper function",
    "Test snapshots",
    "Testing modules",
    "System tests",
    "Deploy to shinyapps.io",
    "Deploying with Docker",
    "Deploying with GitHub Actions (styling code)",
    "Deploying shiny app with GitHub Actions",
    "Deploying shiny app with Docker and GitHub Actions",
    "Deploying a package website",
    "LLMs with Shiny Assistant",
    "LLMs with ellmer package",
    "LLMs with shinychat",
    "LLMs with chores package",
    "golem framework",
    "leprechaun framework",
    "rhino framework",
    "Development branch",
    "gh-pages branch for pkgdown",
    "main (initial) branch"
  )
)
usethis::use_data(topic_lookup, overwrite = TRUE)
